# Generated by Django 2.1.1 on 2018-10-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lenovothink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('brand', models.CharField(max_length=10)),
                ('harddrive', models.CharField(max_length=5)),
                ('value', models.DecimalField(decimal_places=2, max_digits=7)),
                ('material', models.CharField(max_length=10)),
            ],
        ),
    ]
