# Generated by Django 2.1.1 on 2018-10-16 22:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lenovo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lenovothink',
            name='user',
            field=models.ForeignKey(default=1, on_delete=True, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
