# Generated by Django 2.1.1 on 2018-10-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenovo', '0002_lenovothink_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lenovothink',
            name='img_url',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
