# Generated by Django 2.1.1 on 2018-10-16 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lenovo', '0003_lenovothink_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lenovothink',
            name='img_url',
        ),
    ]
